-- Generated by Oracle SQL Developer Data Modeler 22.2.0.165.1149
--   at:        2023-02-28 14:32:31 AEDT
--   site:      Oracle Database 12c
--   type:      Oracle Database 12c



DROP TABLE activity CASCADE CONSTRAINTS;

DROP TABLE goal CASCADE CONSTRAINTS;

DROP TABLE password CASCADE CONSTRAINTS;

DROP TABLE "USER" CASCADE CONSTRAINTS;

-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE activity (
    activity_id     NUMBER NOT NULL,
    activity_name   VARCHAR2(32 CHAR) NOT NULL,
    activity_desc   VARCHAR2(500 CHAR) NOT NULL,
    activity_impact VARCHAR2(500 CHAR) NOT NULL,
    goal_id         NUMBER NOT NULL
);

COMMENT ON COLUMN activity.activity_id IS
    'The activity id used to specified to one unique activity (even with same name).';

COMMENT ON COLUMN activity.activity_name IS
    'Activity name';

COMMENT ON COLUMN activity.activity_desc IS
    'activity descripiton';

COMMENT ON COLUMN activity.activity_impact IS
    'the impact of activity.';

COMMENT ON COLUMN activity.goal_id IS
    'Goal id used to identified a specified goal';

ALTER TABLE activity ADD CONSTRAINT activity_pk PRIMARY KEY ( activity_id );

CREATE TABLE goal (
    goal_id            NUMBER NOT NULL,
    goal_name          VARCHAR2(32 CHAR) NOT NULL,
    goal_desc          VARCHAR2(500 CHAR) NOT NULL,
    goal_initial_state NUMBER(1, 4) NOT NULL,
    goal_current_state NUMBER(1, 4) NOT NULL,
    goal_date          DATE NOT NULL,
    user_id            NUMBER NOT NULL
);

COMMENT ON COLUMN goal.goal_id IS
    'Goal id used to identified a specified goal';

COMMENT ON COLUMN goal.goal_name IS
    'Goal name';

COMMENT ON COLUMN goal.goal_desc IS
    'goal description';

COMMENT ON COLUMN goal.goal_initial_state IS
    'Initial state of goal, represent by number.';

COMMENT ON COLUMN goal.goal_current_state IS
    'Current state of goal, represent by number.';

COMMENT ON COLUMN goal.goal_date IS
    'The date of goal created.';

COMMENT ON COLUMN goal.user_id IS
    'User id used to identied by one sepecifed user.';

ALTER TABLE goal ADD CONSTRAINT goal_pk PRIMARY KEY ( goal_id );

CREATE TABLE password (
    password_id NUMBER NOT NULL,
    pwd         VARCHAR2(32 CHAR) NOT NULL,
    user_id     NUMBER NOT NULL
);

COMMENT ON COLUMN password.password_id IS
    'The password id is unique and each only identified by one password which belong to one user.';

COMMENT ON COLUMN password.pwd IS
    'User''s password which should be at least longer than 8 for secure reason.';

COMMENT ON COLUMN password.user_id IS
    'User id used to identied by one sepecifed user.';

CREATE UNIQUE INDEX password__idx ON
    password (
        user_id
    ASC );

ALTER TABLE password ADD CONSTRAINT password_pk PRIMARY KEY ( password_id,
                                                              user_id );

CREATE TABLE "USER" (
    user_id       NUMBER NOT NULL,
    user_username NUMBER NOT NULL,
    user_email    VARCHAR2(32 CHAR)
);

COMMENT ON COLUMN "USER".user_id IS
    'User id used to identied by one sepecifed user.';

COMMENT ON COLUMN "USER".user_username IS
    'user_username which is created by users.';

COMMENT ON COLUMN "USER".user_email IS
    'user''s email.';

ALTER TABLE "USER" ADD CONSTRAINT user_pk PRIMARY KEY ( user_id );

ALTER TABLE activity
    ADD CONSTRAINT goal_activity FOREIGN KEY ( goal_id )
        REFERENCES goal ( goal_id );

ALTER TABLE password
    ADD CONSTRAINT password_user FOREIGN KEY ( user_id )
        REFERENCES "USER" ( user_id );

ALTER TABLE goal
    ADD CONSTRAINT user_goal FOREIGN KEY ( user_id )
        REFERENCES "USER" ( user_id );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             4
-- CREATE INDEX                             1
-- ALTER TABLE                              7
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- TSDP POLICY                              0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
